name: screendapt
description: "Screendapt provides responsive UI components, making use of the flutter_screenutil package."
version: 0.0.1-dev.2
homepage: https://github.com/Kodrillar/screendapt

environment:
  sdk: ">=3.2.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
